name: Build and Publish
run-name: Building and Publication triggered by ${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ğŸ— Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”§ Install Toolchain
        id: install_toolchain_step
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - name: ğŸ¬ Setup Caching
        id: setup_caching_step
        uses: Swatinem/rust-cache@v2
      - name: ğŸ’¿ Install Dioxus-CLI
        id: install_dioxus_cli_step
        shell: bash
        run: cargo install dioxus-cli --locked
      - name: ğŸŸ Checkout Git Repository
        id: checkout_repository_step
        uses: actions/checkout@v3        
      - name: ğŸ”¨ Build Project
        id: build_project_step
        run: |
          dx build --release --features web \
          && nohup cargo run --release --features prebuild & \
          && cp dist/index.html dist/404.html
          echo "Contents of the dist directory: "
          ls -l dist
      - name: â¬† Upload Artifact
        id: upload_artifact_step
        uses: actions/upload-artifact@v3
        with: 
          name: Website
          path: dist
          if-no-files-found: error
  release:  
    needs: build        
    name: ğŸ‰ Publish
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Download Artifact
        id: download_artiface_step
        uses: actions/download-artifact@v3
        with:
          name: Website
          path: dist
      - name: âœ”ï¸ Verify Artifact
        id: verify_artifact_step
        run: |
          echo "Contents of the dist directory after downloading the artifact: "
          ls -l dist
      - name: â¡ï¸ Push to the Website Repository
        id: push_website_step
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:          
          source-directory: 'dist'
          destination-github-username: 'shiva-patt'
          destination-repository-name: 'shiva-patt.github.io'
          user-name: 'shiva-patt-work'
          user-email: shiva.patt.work@gmail.com
          target-branch: main
          create-target-branch-if-needed: true
       
